export const FOOTER_ACTION = "FOOTER_ACTION";
export const FOOTER_CLOSE = "FOOTER_CLOSE";
export const CERT_ACTION = "CERT_ACTION";
export const CREATE_FILES = "CREATE_FILES";
export const CREATE_FILES_SUCCESS = "CREATE_FILES_SUCCESS";
export const CREATE_FILES_ERROR = "CREATE_FILES_ERROR";